name: Test and Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format check
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Run tests
        run: deno test --allow-read --allow-write